trigger:
- '*'

pool:
  #vmImage: ubuntu-latest
  name: 'onpremise'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

# Install gulp-cli globally to ensure it's available for the pipeline
- task: Npm@1
  displayName: 'Install Gulp CLI'
  inputs:
    command: 'custom'
    customCommand: 'install -g gulp-cli'

# Use script task to run gulp instead of the gulp task
- script: 'gulp'
  displayName: 'Run gulp tasks'
  # If you need to run specific gulp tasks, you can specify them like: 'gulp task1 task2'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'