# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  #vmImage: 'windows-latest'
  name: 'almalinux'

steps:
- task: NuGetCommand@2
  displayName: 'Run Nuget command'
  inputs:
    command: 'restore'
    
- task: DotNetCoreCLI@1
  displayName: 'Build DotNet'
  inputs:
    command: 'build'
    arguments: '--configuration Release'
    projects: '**/*.csproj'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'artifact'
    publishLocation: 'pipeline'