trigger:
- '*'

pool:
  #vmImage: ubuntu-latest
  name: 'onpremise'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

# Make sure gulp is in the package.json and use the local version
- task: Npm@1
  displayName: 'Install gulp locally'
  inputs:
    command: 'custom'
    customCommand: 'install gulp --save-dev'

# Use the local gulp from node_modules
- script: './node_modules/.bin/gulp'
  displayName: 'Run gulp tasks'
  # If you need specific gulp tasks, use: './node_modules/.bin/gulp task1 task2'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'